language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
after_success:
  - ./node_modules/.bin/mocha src/__tests__/*.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js