language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
env:
  - DATABASE_URL_TEST="postgres://postgres@localhost:5432/dev_barefoot_test"
before_script:
  - psql -c 'create database dev_barefoot_test;' -U postgres
after_success:
  - npm run coveralls
